### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by DavZim** [r-lib/cachem#36]
Hi all,
I want to use the `read_fn`/`write_fn` of `cache_disk`, introduced with #31 (version 1.0.6.9000) but currently the CRAN version is at 1.0.6 without that functionality. For testing I can install the dev version, but for production I would like to depend on CRAN...

Is there any plan for a next CRAN release? Is there anything that I can support you with?

Thanks

**Comment by wch** [comment]
@DavZim It's probably time to do a release, so I'll get that started now.
