### ISSUE TITLE
Speed up `set()` resp. `prune()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/cachem#4]
I use `memoise()` to cache requests to an API. As the API is relatively fast I noticed how over time it got slower and slower. After some digging I found that quite a bit of time is spend in `prune()` which is called every time in `set()`.
For longer running functions the overhead is relatively small but for fast ones it would be great to make this a bit more efficient.

Code to replicate

```r
f <- function(x) {
  x
}

f_mem <- memoise::memoise(f)

purrr::walk(1:10e3, f_mem)

profvis::profvis({purrr::walk(10e3 + 1:1e3, f_mem)})
```

![image](https://user-images.githubusercontent.com/18258854/106746875-6fc4f780-6623-11eb-803b-ea98048d41fe.png)

**Comment by wch** [comment]
Thanks for the report. The performance of pruning could definitely be improved. In the meantime, you can use the old-style caching objects which don't do any pruning.

**Comment by wch** [comment]
@mgirlich Can you install from GitHub and try it out?

```R
remotes::install_github("r-lib/cachem")
```

**Comment by wch** [comment]
FYI, the updated version (1.0.2) is already on CRAN.

I'm reopening this issue because there's still room for improvement, although it will require more sophisticated data structures. Currently, calling `$get()` is pretty cheap, but `$set()` is relatively expensive because of the pruning, even with the changes in #5.

**Comment by mgirlich** [comment]
thanks, amazing reaction time! It is quite a nice speed improvement (setting 5.000 elements took ~ 114 s before and ~ 14 s now).
